In [1]:
import numpy as np


In [2]:
a = np.zeros((10, 10), dtype = int1
            )

NameError: name 'int1' is not defined

In [3]:
a = np.zeros((10, 10), dtype = np.int1)

AttributeError: module 'numpy' has no attribute 'int1'

In [4]:
a = np.zeros((10, 10), dtype = np.int2)

AttributeError: module 'numpy' has no attribute 'int2'

In [5]:
a = np.zeros((10, 10), dtype = np.int64)

In [6]:
a = np.zeros((10, 10), dtype = np.int8)

In [7]:
a = np.zeros((10, 10), dtype = np.int4)

AttributeError: module 'numpy' has no attribute 'int4'

In [8]:
a = np.zeros((10, 10), dtype = np.boolean
            )

AttributeError: module 'numpy' has no attribute 'boolean'

In [9]:
a = np.zeros((10, 10), dtype = np.bool?)

SyntaxError: invalid syntax (<ipython-input-9-1f5a7236d674>, line 1)

In [10]:
a = np.zeros((10, 10), dtype = np.bool)

In [11]:
a

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]], dtype=bool)

In [12]:
np.genfromtxt('/code/data/label.txt
              ')

SyntaxError: EOL while scanning string literal (<ipython-input-12-d067f1ecd9fe>, line 1)

In [13]:
np.genfromtxt('/code/data/label.txt')

OSError: /code/data/label.txt not found.

In [14]:
np.genfromtxt('/code/data/labels.txt')

FileNotFoundError: [Errno 2] No such file or directory: '/code/data/labels.txt'

In [15]:
np.genfromtxt('./code/data/labels.txt')

array([ 1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
        1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,
       -1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
        1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
       -1., -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1.,
        1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1.,
        1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,
       -1.,  1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1

In [16]:
a = np.genfromtxt('./code/data/labels.txt')

In [17]:
a.dim()

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [18]:
a.shape()

TypeError: 'tuple' object is not callable

In [19]:
a.shape

(630,)

In [20]:
a[:599]

array([ 1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,
        1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
        1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,
       -1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
        1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
       -1., -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1.,
        1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1.,
        1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,
       -1.,  1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1

In [21]:
%run './code/src/twitter.py'

ERROR:root:File `"'./code/src/twitter.py'.py"` not found.


In [22]:
%run './code/src/twitter'

ERROR:root:File `"'./code/src/twitter'.py"` not found.


In [3]:
%run ./code/src/twitter.py

(630, 1811)


In [3]:
d

NameError: name 'd' is not defined

In [13]:
with open('./code/data/tweets.txt', 'rU') as fid:
    for line in fid:
        print(line)

2012, Micheal:This Is it && A Christmas Carol Are Cool Movies

2012 was the worst... should''ve saw christmas carol in 3d...

a christmas carol. good movie, but some scenes were scary! not a movie for little kids! now, onto watching "christmas vacation".

A Christmas Carol in 3D is AMAZING! The people look so real!

A Christmas carol is possibly the shittest movie ever, I just fell asleep

A christmas carol was amazing :) and alice in wonderland looks freaky!!! I'm excited!

A Christmas Carol was just great...I love Jim Carrey =)

A Christmas Carol was pretty cool...and I looooove 3D!

A Christmas Carol was quite heartwarming. No really, this Pixar movie almost made me cry. Now I want Christmas.

Also saw Christmas Carol in 3D at the cinema, marvelous implementation of technology and Carrey great, but added little to original story

back frm Disney's A Christmas Carol w/ Jim Carey in 3D... it was ok. kinda boring. #achristmascarol

breee breee guess what movie i watched??????? christma

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 'U' mode is deprecated
  """Entry point for launching an IPython kernel.


UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1344: illegal multibyte sequence

In [5]:
%run ./code/src/twitter.py

(630, 1811)


In [6]:
a

NameError: name 'a' is not defined

In [7]:
a = np.genfromtxt('./code/data/labels.txt')

In [8]:
a[a==-1] = 1

In [9]:
a

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [10]:
if 1 == 2:

SyntaxError: unexpected EOF while parsing (<ipython-input-10-af000e574aac>, line 1)

In [11]:
if 1 == 2:

SyntaxError: unexpected EOF while parsing (<ipython-input-11-af000e574aac>, line 1)

In [12]:
if 1 == 2:
    a = 1
print(a)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1

In [13]:
if 1 == 2:
    b = 1
print(b)

NameError: name 'b' is not defined

In [14]:
np.sign([1,2,0])

array([1, 1, 0])

In [15]:
np.sign([1,2,0, -1])

array([ 1,  1,  0, -1])

In [16]:
array([1,2,3])

NameError: name 'array' is not defined

In [17]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [23]:
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)
print(skf) 
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [1 3] TEST: [0 2]
[[3 4]
 [3 4]]
TRAIN: [0 2] TEST: [1 3]
[[1 2]
 [1 2]]


In [24]:
X[1 2]

SyntaxError: invalid syntax (<ipython-input-24-8a980a8cf181>, line 1)

In [25]:
X[1,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [26]:
X[np.array([1,2])]

array([[3, 4],
       [1, 2]])

In [27]:
np.array([1,2,3])

array([1, 2, 3])

In [28]:
print(np.array([1,2,3]))

[1 2 3]


In [30]:
print(X)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [31]:
skf.split(X, y)

<generator object _BaseKFold.split at 0x0000029DC0C6E258>

In [32]:
print(skf.split(X, y))

<generator object _BaseKFold.split at 0x0000029DC0C6E888>


In [33]:
10.0 ** np.arange(-3, 3)

array([  1.00000000e-03,   1.00000000e-02,   1.00000000e-01,
         1.00000000e+00,   1.00000000e+01,   1.00000000e+02])

In [34]:
np.array([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.array([i for i in range(10, -1)])

array([], dtype=float64)

In [39]:

np.array(i for i in range(10, 1, -1))

array(<generator object <genexpr> at 0x0000029DC0C6ED00>, dtype=object)

In [46]:
%run ./code/src/twitter.py

(630, 1811)
Linear SVM Hyperparameter Selection based on accuracy:
accuracy: 
[ 0.66350026  0.7304207   0.78131954  0.78751816  0.78590546  0.78590546]
Linear SVM Hyperparameter Selection based on F1-Score:
F1-Score: 
[ 0.79771418  0.81918909  0.83902927  0.83777158  0.83608265  0.83608265]
Linear SVM Hyperparameter Selection based on AUROC:
AUROC: 
[ 0.5         0.63756855  0.73871499  0.75574157  0.75567186  0.75567186]


In [44]:
from sklearn.cross_validation import StratifiedKFold
skf = StratifiedKFold()


TypeError: __init__() missing 1 required positional argument: 'y'

In [47]:
10**-3

0.001

In [48]:
%run ./code/src/twitter.py

(630, 1811)
Linear SVM Hyperparameter Selection based on accuracy:
[ 0.66350026  0.7304207   0.78131954  0.78751816  0.78590546  0.78590546]
Linear SVM Hyperparameter Selection based on F1-Score:
[ 0.79771418  0.81918909  0.83902927  0.83777158  0.83608265  0.83608265]
Linear SVM Hyperparameter Selection based on AUROC:
[ 0.5         0.63756855  0.73871499  0.75574157  0.75567186  0.75567186]


In [51]:
%run ./code/src/twitter.py

(630, 1811) (630,) (0, 1811) (0,)
Linear SVM Hyperparameter Selection based on accuracy:
[ 0.66350026  0.7304207   0.78131954  0.78751816  0.78590546  0.78590546]
Linear SVM Hyperparameter Selection based on F1-Score:
[ 0.79771418  0.81918909  0.83902927  0.83777158  0.83608265  0.83608265]
Linear SVM Hyperparameter Selection based on AUROC:


KeyboardInterrupt: 

In [2]:
%run ./code/src/twitter.py

(560, 1811) (560,) (70, 1811) (70,)
Linear SVM Hyperparameter Selection based on accuracy:
[ 0.70894195  0.71074376  0.80603268  0.81462711  0.81818274  0.81818274]
Linear SVM Hyperparameter Selection based on F1-Score:
[ 0.82968282  0.8305628   0.87547268  0.87486483  0.87656215  0.87656215]
Linear SVM Hyperparameter Selection based on AUROC:
[ 0.5         0.503125    0.71878716  0.75311133  0.75917194  0.75917194]
Linear SVM Test based on accuracy:0.742857142857
Linear SVM Test based on F1-Score:0.4375
Linear SVM Test based on AUROC:0.625850340136
